title: 일상기록기
description: better than yesterday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bigsan2.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name: bigsan224
author-image: 13.jpeg
author-job: Security Engineer
author-email: bigsan224@gmail.com # Add your email for contant form.
author-twitter: bigsan224 # Add your twitter account
about-author: I am a Security Engineer. Always hungry to keep learning.

# Social settings
social-twitter: bigsan224
social-facebook:
social-github: bigsan2
social-pinterest: bigsan224
social-instagram: 94.swxx
social-youtube:
social-vk:
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
